export enum FORM_TYPE_ENUM {
  GelInternshipAbroad = 'gel_internship_abroad',
  GelSemesterAtSea = 'gel_semester_at_sea',
  SpecializedSkill = 'specialized_skill',
  Entrepreneurship = 'entrepreneurship',
  GelStudyAbroad = 'gel_study_abroad',
  Certification = 'certification',
  GelLanguage = 'gel_language',
  Investment = 'investment',
  Employment = 'employment',
  Internship = 'internship',
  GelTravel = 'gel_travel',
  Volunteer = 'volunteer',
  Athletic = 'athletic',
  Academic = 'academic',
  Custom = 'custom',
  Talent = 'talent',
  Award = 'award',
  Tech = 'tech',
  Club = 'club',
  Art = 'art',
}
